version: "3.8"

services:
  messageboard:
    image: ${messageboard_image}
    container_name: messageboard
    env_file: .env
    ports:
      - "8000:8000"
    networks:
      - backend

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "8888:80"
      - "443:443"
    volumes:
      - ${nginx_config_path}:/etc/nginx/conf.d/default.conf:ro
      - ${nginx_ssl_path}:/etc/nginx/ssl:ro
    depends_on:
      - messageboard
    networks:
      - backend

networks:
  backend:
